MODEL:
  META_ARCHITECTURE: "SAM"
  WEIGHTS: "facebook/sam-vit-base"
DATASETS:
  TEST: ("ade20k_sem_seg_val",)
INPUT:
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 1024 # SAM input size
  FORMAT: "RGB"
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
VERSION: 2
SEED: 42
PROMPT_TYPE: "points"
IGNORE_BACKGROUND: False